version: "3"

services:
    frontend:
        build: ./frontend
        ports:
            - "3000:80" # Map host port 3000 to container port 80 (Nginx default)
        environment: 
            REACT_APP_AUTH_SERVICE_LOCAL_URL: http://apigateway:3003
            REACT_APP_CODE_EXECUTION_LOCAL_URL: http://apigateway:3003/code-execution
            REACT_APP_COLLABORATION_SERVICE_LOCAL_URL: http://collaboration-service:3004
            REACT_APP_MATCHING_SERVICE_LOCAL_URL: http://matching-service:3006
            REACT_APP_QUESTION_SERVICE_LOCAL_URL: http://apigateway:3003/question
            REACT_APP_USER_SERVICE_LOCAL_URL: http://apigateway:3003/user


    apigateway:
        build: ./api-gateway
        ports:
            - "3003:3003"
        depends_on:
            - user-service
            - question-service
            - code-execution-service
        environment:
            USER_SERVICE_URL: http://user-service:3001
            QUESTION_SERVICE_URL: http://question-service:3002
            CODE_EXECUTION_SERVICE_URL: http://code-execution-service:3005

    question-service:
        build: ./question-service
        ports:
            - "3002:3002"

    user-service:
        build: ./user-service
        ports:
            - "3001:3001"

    matching-service:
        build: ./matching-service
        ports:
            - "3006:3006"
        depends_on:
            - redis
            - question-service
            - collaboration-service
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            QUESTION_SERVICE_URL: http://question-service:3002/
            COLLABORATION_SERVICE_URL: http://collaboration-service:3004/
        restart: on-failure

    collaboration-service:
        build: ./collaboration-service
        ports:
            - "3004:3004"
        depends_on:
            - question-service
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            QUESTION_SERVICE_URL: http://question-service:3002/
        restart: on-failure

    code-execution-service:
        build: ./code-execution-service
        ports:
            - "3007:3007"

    redis:
        image: redis
        container_name: redis-server
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
