#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-execution-service
  template:
    metadata:
      labels:
        app: code-execution-service
    spec:
      containers:
      - name: code-execution-service
        image: tehopanas/code-execution-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3005

---

apiVersion: v1
kind: Service
metadata:
  name: code-execution-service
spec:
  selector:
    app: code-execution-service
  ports:
  - port: 3005
    targetPort: 3005
  type: ClusterIP
