# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - name: collaboration-service
        image: tehopanas/collaboration-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3004

---

apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
spec:
  selector:
    app: collaboration-service
  ports:
  - port: 3004
    targetPort: 3004
  type: ClusterIP
