# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - name: collaboration-service
        image: tehopanas/cs3219-collaboration-service:latest
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
          - name: QUESTION_SERVICE_URL
            value: http://question-service.default.svc.cluster.local:3002/
          - name: FRONTEND_URL
            value: http://frontend.default.svc.cluster.local:3000/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3004

---

apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
spec:
  selector:
    app: collaboration-service
  ports:
  - port: 3004
    targetPort: 3004
  type: LoadBalancer
